# Generated by Django 4.0.4 on 2022-05-03 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fishname', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('latitude', models.CharField(blank=True, max_length=200)),
                ('longitude', models.CharField(blank=True, max_length=200)),
                ('image', models.FileField(blank=True, upload_to='upload/image')),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
